language: python
python:
  - "3.7"

services:
  - docker

before_script:
  - pip install docker-compose
  - docker-compose up -d

scirpt:
  - docker-compose run app sh -c "python manage.py test && flake8"