version: "3"

services: 
  app:
    container_name: 'recipe_api'
    restart: always
    build:
      context: ./api
    ports: 
      - "8000:8000"
    volumes: 
      - ./api:/usr/src/app/api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword@1
    depends_on: 
      - db
  
  db:
    container_name: 'postgres'
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword@1