version: "3"

services: 
  app:
    container_name: 'recipe_api'
    restart: always
    build:
      context: ./api
    ports: 
      - "8000:8000"
    volumes: 
      - ./api:/usr/src/app/api
    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword@1
    depends_on: 
      - db
  
  db:
    image: postgres:10-alpine
    ports:
     - "5432:5432"
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword@1